inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - app/javascript/**/*
    - bin/**/*
    - coverage/**/*
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - spec/javascript/**/*
    - tmp/**/*
    - vendor/**/*
    - docker-volumes/**/*
  EnabledByDefault: true

### Rails

Rails/SkipsModelValidations:
  Enabled: false

Rails/SaveBang:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/ApplicationController:
  Enabled: false

Rails/SchemaComment:
  Enabled: false

Rails/EnvironmentVariableAccess:
  AllowReads: true

### Bundler

Bundler/OrderedGems:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

### Style

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IpAddresses:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/RequireOrder:
  Enabled: false

### Layout

Layout/LineLength:
  Max: 190
  AllowedPatterns: ['\A#'] # Allow long comments

### Metrics

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

# Lint

Lint/ConstantResolution:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

# Performance

Performance/ChainArrayAllocation:
  Enabled: false

# RSpec

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false
